name: Create VPC and EC2 Instance

on:
    workflow_dispatch:

jobs:
    create-vpc-and-ec2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.0.0

            - name: Initialize Terraform
              run: |
                cd practice/VPCandEc2
                terraform init

            - name: Terraform Plan
              run: |
                cd practice/VPCandEc2  
                terraform plan
            
            - name: Terraform validate
              run: |
                cd practice/VPCandEc2
                terraform validate

            - name: Apply Terraform
              run: |
                cd practice/VPCandEc2
                terraform apply -auto-approve

            - name: Output VPC ID
              run: echo "VPC ID is $(terraform output vpc_id)"